module.exports = {
  resolve: 'gatsby-plugin-favicon',
  options: {
    logo: './src/images/icon.png',
    appName: 'Pod Volit',
    appDescription: 'Pod Volit',
    developerName: 'Pod Volit',
    developerURL: null,
    dir: 'auto',
    lang: 'en-US',
    theme_color: '#209cee',
    display: 'standalone',
    orientation: 'any',
    start_url: '/',
    version: '1.0',
    icons: {
      android: true,
      appleIcon: true,
      appleStartup: true,
      coast: false,
      favicons: true,
      firefox: true,
      opengraph: false,
      twitter: false,
      yandex: false,
      windows: false,
    },
  },
};
